on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
      - name: install python packages
        run: |
          #lscpu
          #sudo apt install sudo 
          #sudo apt upgrade
          #sudo apt autoremove
          #sudo apt --fix-broken install
          #pip install -r requirements.txt

      - name: run  # run main.py
        run:  sudo python 1.py
      - name: get # run main.py
        run: |
          rm chrome-remote-desktop_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb
          python3 s.py
