on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          #lscpu
          sudo apt update
          sudo apt upgrade
          sudo apt autoremove
          sudo apt --fix-broken install
          #pip install -r requirements.txt

      - name: run  # run main.py
        run: sudo python3 1.py
      - name: get # run main.py
        run: |
          rm chrome-remote-desktop_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb
          python3 s.py
